site_name: Daiquiri documentation

nav:
  - Home: index.md
  - Installation: installation.md
  - Deployment: deployment.md
  - Settings: settings.md
  - Administration: administration.md
  - Management: management.md
  - Advanced features: advanced.md
  - OAI Metadata: oai-metadata.md

theme:
    name: readthedocs

markdown_extensions:
- def_list
- footnotes
- tables
- smarty

extra_css:
  - style.css
