# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Generate docs and trigger deployment'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gen-and-trigger:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - run: pip install -r requirements.txt
    - run: mkdocs gh-deploy
