# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gen-and-trigger:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3.3.0
    - run: /usr/bin/git fetch --all
    - run: /usr/bin/git pull --ff-only origin master
    - run: /usr/bin/git checkout gh-pages
    - run: /usr/bin/git pull --ff-only origin gh-pages
    - run: /usr/bin/git checkout master
    - uses: py-actions/py-dependency-install@v4.0.0
    - run: mkdocs gh-pages
